[package]
name = "egui_select2"
version = "0.1.0"
edition = "2024"
authors = ["Thomas Bellembois <thomas.bellembois@proton.me>"]
description = "A select2 like multi select widget for egui"
license = "GPL-3.0"
repository = "https://github.com/tbellembois/egui_select2"
homepage = "https://github.com/tbellembois/egui_select2"
readme = "README.md"
categories = ["database", "science"]
keywords = ["egui","select2", "widget"]
rust-version = "1.92.0"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# unwrap_used = "warn"
# expect_used = "warn"
# panic = "warn"
# unreachable = "warn"

missing_errors_doc = "allow"
missing_panics_doc = "allow"
struct_excessive_bools = "allow"
too_many_lines = "allow"

[dependencies]
eframe = { version = "0.35.0" }
egui = { version = "0.35.0", default-features = false }
log =  { version = "0.4.29", default-features = false }
rand = { version = "0.7", default-features = false, features = ["wasm-bindgen", "std"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.150", default-features = false, features = ["std"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.68"

[dev-dependencies]
egui_extras = { version = "0.35.0", features = ["all_loaders"] }
image = { version = "0.25", features = ["png"] }
ehttp = "0.7.1"
egui_logger = "0.10.0"

[[example]]
name = "basic"
path = "examples/src/basic.rs"

[[example]]
name = "pictures"
path = "examples/src/pictures.rs"

[[example]]
name = "remote"
path = "examples/src/remote.rs"

[[example]]
name = "disabled"
path = "examples/src/disabled.rs"

[[example]]
name = "several"
path = "examples/src/several.rs"

[[example]]
name = "long"
path = "examples/src/long.rs"

[[example]]
name = "validate"
path = "examples/src/validate.rs"
